name: AI Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ai-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI Code Review Action
        uses: aidar-freeed/ai-codereviewer@v2.7.0
        with:
          open_ai_model: gpt-3.5-turbo
          with-comment: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
